application:
  host: "0.0.0.0"
  port: 8000
  readTimeout: 120s
  writeTimeout: 120s
client:
  timeout: 30s
  retryCount: 3
  retrySleepTime: 5s
log:
  dir: "E:\\fly\\my-git\\webhook\\log"
  rotate:
    # MB
    maxSize: 10
    maxBackups: 10
webhooks:
  dingtalk-from-sentry-aimfulbbmldb:
    url: "http://11sss"
    method: "POST"
    # default: application/json
    contentType: application/json
    query:
      - name: "ipByQuery"
        value: "{{ .ip_by_query }}"
      - name: "ipByBody"
        value: "{{ .ip_by_body }}"
    header:
      - name: "ipByQuery"
        value: "{{ .ip_by_query }}"
      - name: "ipByBody"
        value: "{{ .ip_by_body }}"
    # not support case sensitive keys: docs: https://github.com/spf13/viper#does-viper-support-case-sensitive-keys
    # varFrom: Query, Body, Header, Value. default: Value
    vars:
      ip_by_body:
        key: "client.ip"
        from: "Body"
      ip_by_query:
        key: "ip"
        value: "default"
        from: "Query"
      content_by_header:
        key: "Content-Type"
        value: "default"
        from: "Header"
    body:
      msgtype: "text"
      text:
        content: "error: template: ipByQuery: {{ .ip_by_query }} ipByBody: {{ .ip_by_body }}"


